version: '3.7'
services:
  # trino:
  #   hostname: trino
  #   image: 'trinodb/trino:366'
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./etc:/etc/trino:ro
  #   networks:
  #     - trino-network

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    hostname: hive-metastore
    image: 'hive-metastore-cw:latest'
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

  # minio:
  #   hostname: minio
  #   image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
  #   container_name: minio
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - minio-data:/data
  #   environment:
  #     MINIO_ACCESS_KEY: minio_access_key
  #     MINIO_SECRET_KEY: minio_secret_key
  #   command: server /data
  #   networks:
  #     - trino-network

  # java_build:
  #   image: maven:3.8.6-openjdk-8-slim
  #   volumes:
  #     - ~/repo:/repo
  #   command: sleep infinity

# volumes:
#   minio-data:
#     driver: local

networks:
  trino-network:
    driver: bridge