#!/bin/sh


export HADOOP_HOME=/opt/hadoop-3.3.3

# Using hadoop-3.3.3 from official website
# export HADOOP_CLASSPATH=${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.1026.jar:${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-3.3.3.jar
# Using custom built hadoop-3.4.0-SNAPSHOT
export HADOOP_CLASSPATH=${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.132.jar:${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-3.4.0-SNAPSHOT.jar

export JAVA_HOME=/usr/local/openjdk-8

# Run hive-metastore with default script
# /opt/apache-hive-metastore-3.0.0-bin/bin/schematool -initSchema -dbType mysql | tee /tmp/initSchema.log
# /opt/apache-hive-metastore-3.0.0-bin/bin/start-metastore

# These CLASSPATHs exclude yarn, mapreduce and tools
# Using hadoop-3.3.3 from official website
# export CLASSPATH=/opt/apache-hive-metastore-3.0.0-bin/conf:/opt/apache-hive-metastore-3.0.0-bin/lib/HikariCP-2.6.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/aircompressor-0.8.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/antlr-runtime-3.5.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/bonecp-0.8.0.RELEASE.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-dbcp-1.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-lang-2.6.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-lang3-3.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-pool-1.5.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-api-jdo-4.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-core-4.1.17.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-rdbms-4.1.19.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/derby-10.10.2.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/dropwizard-metrics-hadoop-metrics2-reporter-0.1.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/guava-19.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hive-standalone-metastore-3.0.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hive-storage-api-2.6.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/httpcore-4.4.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-annotations-2.9.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-core-2.9.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-databind-2.9.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/javax.jdo-3.2.0-m3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/javolution-5.5.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jline-2.14.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/libfb303-0.9.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/libthrift-0.9.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-1.2-api-2.8.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-api-2.8.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.8.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-slf4j-impl-2.8.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-core-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-json-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-jvm-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/mysql-connector-java-8.0.19.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/orc-core-1.4.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/protobuf-java-2.5.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/sqlline-1.3.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/transaction-api-1.1.jar:/opt/hadoop-3.3.3/share/hadoop/aws-java-sdk-bundle-1.11.1026.jar:/opt/hadoop-3.3.3/share/hadoop/hadoop-aws-3.3.3.jar:/opt/hadoop-3.3.3/etc/hadoop:/opt/hadoop-3.3.3/share/hadoop/common/lib/*:/opt/hadoop-3.3.3/share/hadoop/common/*:/opt/hadoop-3.3.3/share/hadoop/hdfs:/opt/hadoop-3.3.3/share/hadoop/hdfs/lib/*:/opt/hadoop-3.3.3/share/hadoop/hdfs/*
# Using custom built hadoop-3.4.0-SNAPSHOT
export CLASSPATH=/opt/apache-hive-metastore-3.0.0-bin/conf:/opt/apache-hive-metastore-3.0.0-bin/lib/HikariCP-2.6.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/aircompressor-0.8.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/antlr-runtime-3.5.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/bonecp-0.8.0.RELEASE.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-dbcp-1.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-lang-2.6.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-lang3-3.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/commons-pool-1.5.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-api-jdo-4.2.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-core-4.1.17.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/datanucleus-rdbms-4.1.19.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/derby-10.10.2.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/dropwizard-metrics-hadoop-metrics2-reporter-0.1.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/guava-19.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hive-standalone-metastore-3.0.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hive-storage-api-2.6.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/httpcore-4.4.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-annotations-2.13.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-annotations-2.9.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-core-2.13.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-core-2.9.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-databind-2.13.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jackson-databind-2.9.4.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/javax.jdo-3.2.0-m3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/javolution-5.5.1.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/jline-2.14.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/libfb303-0.9.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/libthrift-0.9.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-1.2-api-2.12.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-api-2.12.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-core-2.12.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/log4j-slf4j-impl-2.12.2.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-core-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-json-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/metrics-jvm-3.1.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/mysql-connector-java-8.0.19.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/orc-core-1.4.3.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/protobuf-java-2.5.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/sqlline-1.3.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/transaction-api-1.1.jar:/opt/hadoop-3.3.3/share/hadoop/aws-java-sdk-bundle-1.12.132.jar:/opt/hadoop-3.3.3/share/hadoop/hadoop-aws-3.4.0-SNAPSHOT.jar:/opt/hadoop-3.3.3/etc/hadoop:/opt/hadoop-3.3.3/share/hadoop/common/*:/opt/hadoop-3.3.3/share/hadoop/common/lib/*

# Using hadoop-3.3.3 from official website
# /usr/local/openjdk-8/bin/java -Dproc_jar -Dproc_metastore  -Dlog4j.configurationFile=metastore-log4j2.properties  -Dyarn.log.dir=/opt/hadoop-3.3.3/logs -Dyarn.log.file=hadoop.log -Dyarn.home.dir=/opt/hadoop-3.3.3 -Dyarn.root.logger=INFO,console -Djava.library.path=/opt/hadoop-3.3.3/lib/native -Xmx256m -Dhadoop.log.dir=/opt/hadoop-3.3.3/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/opt/hadoop-3.3.3 -Dhadoop.id.str=hive -Dhadoop.root.logger=INFO,console -Dhadoop.policy.file=hadoop-policy.xml -Dhadoop.security.logger=INFO,NullAppender org.apache.hadoop.util.RunJar /opt/apache-hive-metastore-3.0.0-bin/lib/hive-standalone-metastore-3.0.0.jar org.apache.hadoop.hive.metastore.HiveMetaStore
# Using custom built hadoop-3.4.0-SNAPSHOT
## Init DB Schema
/usr/local/openjdk-8/bin/java -Dproc_jar -Djava.net.preferIPv4Stack=true  -Dlog4j.configurationFile=metastore-log4j2.properties -Dyarn.log.dir=/opt/hadoop-3.3.3/logs -Dyarn.log.file=hadoop.log -Dyarn.home.dir=/opt/hadoop-3.3.3 -Dyarn.root.logger=INFO,console -Xmx256m -Dhadoop.log.dir=/opt/hadoop-3.3.3/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/opt/hadoop-3.3.3 -Dhadoop.id.str=hive -Dhadoop.root.logger=INFO,console -Dhadoop.policy.file=hadoop-policy.xml -Dhadoop.security.logger=INFO,NullAppender org.apache.hadoop.util.RunJar /opt/apache-hive-metastore-3.0.0-bin/lib/hive-standalone-metastore-3.0.0.jar org.apache.hadoop.hive.metastore.tools.MetastoreSchemaTool -initSchema -dbType mysql
## Run metastore
/usr/local/openjdk-8/bin/java -Dproc_jar -Dproc_metastore  -Dlog4j.configurationFile=metastore-log4j2.properties  -Dyarn.log.dir=/opt/hadoop-3.3.3/logs -Dyarn.log.file=hadoop.log -Dyarn.home.dir=/opt/hadoop-3.3.3 -Dyarn.root.logger=INFO,console -Xmx256m -Dhadoop.log.dir=/opt/hadoop-3.3.3/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/opt/hadoop-3.3.3 -Dhadoop.id.str=hive -Dhadoop.root.logger=INFO,console -Dhadoop.policy.file=hadoop-policy.xml -Dhadoop.security.logger=INFO,NullAppender org.apache.hadoop.util.RunJar /opt/apache-hive-metastore-3.0.0-bin/lib/hive-standalone-metastore-3.0.0.jar org.apache.hadoop.hive.metastore.HiveMetaStore